# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


app_name = 'geonames'
urlpatterns = [
    url(
        regex="^Country/~create/$",
        view=views.CountryCreateView.as_view(),
        name='Country_create',
    ),
    url(
        regex="^Country/(?P<pk>\d+)/~delete/$",
        view=views.CountryDeleteView.as_view(),
        name='Country_delete',
    ),
    url(
        regex="^Country/(?P<pk>\d+)/$",
        view=views.CountryDetailView.as_view(),
        name='Country_detail',
    ),
    url(
        regex="^Country/(?P<pk>\d+)/~update/$",
        view=views.CountryUpdateView.as_view(),
        name='Country_update',
    ),
    url(
        regex="^Country/$",
        view=views.CountryListView.as_view(),
        name='Country_list',
    ),
	url(
        regex="^GeonamesAdm1/~create/$",
        view=views.GeonamesAdm1CreateView.as_view(),
        name='GeonamesAdm1_create',
    ),
    url(
        regex="^GeonamesAdm1/(?P<pk>\d+)/~delete/$",
        view=views.GeonamesAdm1DeleteView.as_view(),
        name='GeonamesAdm1_delete',
    ),
    url(
        regex="^GeonamesAdm1/(?P<pk>\d+)/$",
        view=views.GeonamesAdm1DetailView.as_view(),
        name='GeonamesAdm1_detail',
    ),
    url(
        regex="^GeonamesAdm1/(?P<pk>\d+)/~update/$",
        view=views.GeonamesAdm1UpdateView.as_view(),
        name='GeonamesAdm1_update',
    ),
    url(
        regex="^GeonamesAdm1/$",
        view=views.GeonamesAdm1ListView.as_view(),
        name='GeonamesAdm1_list',
    ),
	url(
        regex="^GeonamesAdm2/~create/$",
        view=views.GeonamesAdm2CreateView.as_view(),
        name='GeonamesAdm2_create',
    ),
    url(
        regex="^GeonamesAdm2/(?P<pk>\d+)/~delete/$",
        view=views.GeonamesAdm2DeleteView.as_view(),
        name='GeonamesAdm2_delete',
    ),
    url(
        regex="^GeonamesAdm2/(?P<pk>\d+)/$",
        view=views.GeonamesAdm2DetailView.as_view(),
        name='GeonamesAdm2_detail',
    ),
    url(
        regex="^GeonamesAdm2/(?P<pk>\d+)/~update/$",
        view=views.GeonamesAdm2UpdateView.as_view(),
        name='GeonamesAdm2_update',
    ),
    url(
        regex="^GeonamesAdm2/$",
        view=views.GeonamesAdm2ListView.as_view(),
        name='GeonamesAdm2_list',
    ),
	url(
        regex="^GeonamesAdm3/~create/$",
        view=views.GeonamesAdm3CreateView.as_view(),
        name='GeonamesAdm3_create',
    ),
    url(
        regex="^GeonamesAdm3/(?P<pk>\d+)/~delete/$",
        view=views.GeonamesAdm3DeleteView.as_view(),
        name='GeonamesAdm3_delete',
    ),
    url(
        regex="^GeonamesAdm3/(?P<pk>\d+)/$",
        view=views.GeonamesAdm3DetailView.as_view(),
        name='GeonamesAdm3_detail',
    ),
    url(
        regex="^GeonamesAdm3/(?P<pk>\d+)/~update/$",
        view=views.GeonamesAdm3UpdateView.as_view(),
        name='GeonamesAdm3_update',
    ),
    url(
        regex="^GeonamesAdm3/$",
        view=views.GeonamesAdm3ListView.as_view(),
        name='GeonamesAdm3_list',
    ),
	url(
        regex="^GeonamesAdm4/~create/$",
        view=views.GeonamesAdm4CreateView.as_view(),
        name='GeonamesAdm4_create',
    ),
    url(
        regex="^GeonamesAdm4/(?P<pk>\d+)/~delete/$",
        view=views.GeonamesAdm4DeleteView.as_view(),
        name='GeonamesAdm4_delete',
    ),
    url(
        regex="^GeonamesAdm4/(?P<pk>\d+)/$",
        view=views.GeonamesAdm4DetailView.as_view(),
        name='GeonamesAdm4_detail',
    ),
    url(
        regex="^GeonamesAdm4/(?P<pk>\d+)/~update/$",
        view=views.GeonamesAdm4UpdateView.as_view(),
        name='GeonamesAdm4_update',
    ),
    url(
        regex="^GeonamesAdm4/$",
        view=views.GeonamesAdm4ListView.as_view(),
        name='GeonamesAdm4_list',
    ),
	url(
        regex="^GeonamesAdm5/~create/$",
        view=views.GeonamesAdm5CreateView.as_view(),
        name='GeonamesAdm5_create',
    ),
    url(
        regex="^GeonamesAdm5/(?P<pk>\d+)/~delete/$",
        view=views.GeonamesAdm5DeleteView.as_view(),
        name='GeonamesAdm5_delete',
    ),
    url(
        regex="^GeonamesAdm5/(?P<pk>\d+)/$",
        view=views.GeonamesAdm5DetailView.as_view(),
        name='GeonamesAdm5_detail',
    ),
    url(
        regex="^GeonamesAdm5/(?P<pk>\d+)/~update/$",
        view=views.GeonamesAdm5UpdateView.as_view(),
        name='GeonamesAdm5_update',
    ),
    url(
        regex="^GeonamesAdm5/$",
        view=views.GeonamesAdm5ListView.as_view(),
        name='GeonamesAdm5_list',
    ),
	url(
        regex="^PopulatedPlace/~create/$",
        view=views.PopulatedPlaceCreateView.as_view(),
        name='PopulatedPlace_create',
    ),
    url(
        regex="^PopulatedPlace/(?P<pk>\d+)/~delete/$",
        view=views.PopulatedPlaceDeleteView.as_view(),
        name='PopulatedPlace_delete',
    ),
    url(
        regex="^PopulatedPlace/(?P<pk>\d+)/$",
        view=views.PopulatedPlaceDetailView.as_view(),
        name='PopulatedPlace_detail',
    ),
    url(
        regex="^PopulatedPlace/(?P<pk>\d+)/~update/$",
        view=views.PopulatedPlaceUpdateView.as_view(),
        name='PopulatedPlace_update',
    ),
    url(
        regex="^PopulatedPlace/$",
        view=views.PopulatedPlaceListView.as_view(),
        name='PopulatedPlace_list',
    ),
	]
